### PR TITLE
Include license files in published crates

### PR DESCRIPTION
**Pull request by ankane**
Hey, thanks for this library!

This PR symlinks the license files so they're included in the published crates (like with sprs 0.11.0).

### CODE REVIEW

**Comment by mulimoen** [comment]
Thanks for the PR. I would think the licenses are fairly well known and not necessary to include. Is there a benefit in adding these files to the published blobs?

**Comment by ankane** [comment]
Hi @mulimoen, both licenses mention including it with copies of the software, and it's nice for things like `cargo vendor` (https://github.com/microsoft/windows-rs/issues/1587#issuecomment-1063010186).

**Comment by mulimoen** [comment]
I see. Thanks for the explanation and the PR!

**Comment by ankane** [comment]
Great, thanks!

**Pull request merged**
